### PR TITLE
Wraps tweepy functionality in a TwitterClient object

### PR DESCRIPTION
**Pull request by jamalhansen**
This allows for easier mocking and less dependence on the Tweepy API in case the underlying tool changes in the future.

### CODE REVIEW

**Comment by jamalhansen** [comment]
try running ./sql_analyze.py from the command line :)

**Comment by jcode89** [comment]
@jamalhansen This looks awesome! And being able to run `./sql_analyze.py` from the command line. Definitely a plus! :smile: Looks good to merge! :+1:

**Comment by jamalhansen** [comment]
Merged, Thank you

**Comment by jcode89** [comment]
Not a problem sir :smile:

**Pull request merged**
