### PR TITLE
Adds a configuration class

### PR DESCRIPTION
**Pull request by jamalhansen**
Creates a configuration class for Issue #5 

Adds Travis CI

Adds Pytest

### CODE REVIEW

**Comment by jcode89** [comment]
@jamalhansen This pull request looks good to me. Definitely sets the project up to be reliable with every new addition.

**Comment by jamalhansen** [comment]
W00t!  I'll go ahead and merge it then :)

**Comment by jamalhansen** [comment]
Unless you want to do the honors

**Comment by jcode89** [comment]
No sir, you should have the honors :smile:

**Comment by jamalhansen** [comment]
Merged!  Thank you :)

**Comment by jcode89** [comment]
:) Not a problem

**Pull request merged**
