### PR TITLE
Updates RethinkDB version 

### PR DESCRIPTION
**Pull request by jcode89**
This pull request addresses some issues with an outdated RethinkDB version. You now get more analysis and can specify the amount of time you want the stream to run. It is in line with the web app version. Addresses issue #8

### CODE REVIEW

**Comment by jcode89** [comment]
@jamalhansen I have readied a pull request to get the RethinkDB version up to date with the web app.

**Comment by jamalhansen** [comment]
Good work!  This looks like it moves the codebase forward.  I hope as we move forward we will make it easier to create tests for this sort of change.  Repeatable tests are not really possible at this point for this sort of change. 

Merge away

**Comment by jcode89** [comment]
I do want to make it easier to create tests, this is the same problem I was running into with the website. I think as we move forward, and things become more streamlined it will become easier.

**Comment by jcode89** [comment]
close #8

**Pull request merged**
